name: CI

on:
  - push

jobs:
  composite_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pione30/github-pages-deploy-composite-action@deploy-steps
        with:
          folder: 'gh-pages'
          folder: 'hello-gh-pages'
