name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  if-omit-expression-syntax-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Explicit expression syntax
        if: ${{ github.actor == 'pione30' }}
        run: echo "Explicitly github.actor is pione30"
      - name: Expression syntax omitted
        if: github.actor == 'pione30'
        run: echo "github.actor is pione30 even though the expression syntax omitted"

      - name: Not operator on the head in the explicit expression syntax
        if: ${{ !startsWith(github.head_ref, 'pione30/') }}
        run: echo "Explicitly github.head_ref does NOT startsWith 'pione30/'"
      - name: Not operator on the head without the expression syntax
        if: (!startsWith(github.head_ref, 'pione30/'))
        run: echo "github.head_ref does NOT startsWith 'pione30/'"

      - name: Verbatim Tags (1)
        if: !<tag:yaml.org,2002:str> startsWith(github.head_ref, 'pione30/')
        run: echo "github.head_ref DOES startsWith 'pione30/'"
      - name: Verbatim Tags (2)
        if: !<tag:yaml.org,2002:str> startsWith(github.head_ref, 'foobar/')
        run: echo "github.head_ref DOES startsWith 'pione30/'"
